sudo: false
language: java
jdk:
  - oraclejdk8
services:
addons:
  postgresql: "9.4"
cache:
  directories:
    - '$HOME/.gradle/caches'
    - '$HOME/.gradle/wrapper'
before_script:
  - psql -c 'create role ft_presentation with login;' -U postgres
  - psql -c 'create database ft_presentation;' -U postgres
script:
  - ./gradlew clean build
