sudo: required
language: java
jdk:
- oraclejdk8
services: 
addons:
  postgresql: '9.5'
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.5-dev
    - python3.5-venv
cache:
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper
  - $HOME/.m2
before_script:
- sudo /etc/init.d/postgresql stop
- sudo apt-get -y remove --purge postgresql-9.1 postgresql-9.2 postgresql-9.3 postgresql-9.4
- sudo apt-get -y autoremove
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7FCC7D46ACCC4CF8
- sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
- sudo apt-get update
- sudo apt-get -y install postgresql-9.5
- sudo sh -c 'echo "local all postgres trust" > /etc/postgresql/9.5/main/pg_hba.conf'
- sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/9.5/main/pg_hba.conf'
- sudo /etc/init.d/postgresql restart
- psql --version
- psql -c 'create database test_openregister_java;' -U postgres
- psql -c 'create database ft_openregister_java;' -U postgres
deploy:
- provider: s3
  access_key_id: AKIAINSAHPOLGXFFYGMQ
  secret_access_key: &1
    secure: IBuHgCLFVPxg35wCStvG6Ec4FB9hm6BvLYZDpMbras5Y5F9gXUQZXDP+BfgZ3fdbY3Nm1TL2KdrG5lcOd2eaVjxDJbBU4IbpyRJUVCNBlBzRhfFfdHNOxMYHsih/T6GF2vOp/nHyyn2zpjS85tsw3CH083zTre+IPSUYEDg4SGyj2RSzgZgZgdETTys9InFShbPAv5F8vEyfU+Y64hzlbRpjCnsNGR2WqxJc1o4qfF1bt8Id/piIoZMTGkBF7VCrXtttIwuJI7AO2dZEqT5DKNGRbUZfIZgRbciAsH70r+Go5p7kK/n6J7Lumu32MoyaMS7kJjHnOjwp3PSRF+d0inyRfaAY176rDTuBeOCnUKj9bMABsxO2Dm5R1SarCSMbQI2dBq6mza7KUpduaVnIJ2iE8DZBC9znpuoc1xQN4F+Q+XhPDwafbodf7SXlJU8EmNTXpLuihsrcRoQSQRslml/fwHGSNB6QhRQrq/RQtpYO5wFk/x84BAndYA0q7ClTzQtDcn0Ns0K0a5BsCdQzfsnsMM06ehshvTo20MnEhWbQ1UrFMYFdf25avZn6H5fJ48JK0w3L7UtWUAzOuYCks/8y9k07VILavNaPDXVmLydgHuUYF8XUXsx+6d7Ax2xKYmpdvRG2FP0j+HPAqVVMRw1M68k8TGeJsiYia3uy/7g=
  local_dir: deployable_bundle
  bucket: openregister.app.artifacts
  region: eu-west-1
  skip_cleanup: true
  on: &2
    branch: master
    condition: $DEPLOY=true
