name: school
database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/presentation
  user: presentation
  properties:
    charSet: UTF-8

zookeeperServer: localhost:2181

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout

