server:
  registerDefaultExceptionMappers: false

database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://${POSTGRES_PORT_5432_TCP_ADDR:-localhost}:${POSTGRES_PORT_5432_TCP_PORT:-5432}/postgres
  user: ${POSTGRES_ENV_POSTGRES_USER:-postgres}
  password: ${POSTGRES_ENV_POSTGRES_PASSWORD:-}
  properties:
    charSet: UTF-8
