database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://postgres:5432/openregister_java
  user: postgres
  password:

  #db connection properties
  initialSize: 1
  minSize: 1
  maxSize: 4

  properties:
    charSet: UTF-8

server:
  registerDefaultExceptionMappers: false
  adminConnectors:
    - type: http
      port: 9092
  requestLog:
    appenders:
      - type: access-logstash-console

registerDomain: 192.168.1.99:4009
registerDomain: register.register-research.cloud

register: datatype
schema: datatype

enableDownloadResource: true

externalConfigDirectory: /tmp

downloadConfigs: true

# can be http: file s3: or classpath: url
#fieldsJsonLocation: http://field/records.json?page-size=5000
#registersJsonLocation: http://register/records.json?page-size=5000
#fieldsJsonLocation: http://field.discovery.reigister.easimap.cloud/records.json
#registersJsonLocation: http://register.discovery.register.easmiap.cloud/records.json
fieldsJsonLocation: classpath://config/fields.json
registersJsonLocation: classpath://config/registers.json

credentials:
  user: foo
  password: bar

# Logging settings.
logging:
  level: INFO
  # Logger-specific levels.
  loggers:
    "uk.gov": DEBUG
    "org.skife.jdbi.v2": TRACE
  appenders:
    - type: logstash-console

registers:
  register:
    schema: register
    enableDownloadResource: True
    enableRegisterDataDelete: True

    credentials:
      user: foo
      password: bar

  field:
    schema: field
    enableDownloadResource: True
    enableRegisterDataDelete: True

    credentials:
      user: foo
      password: bar