version: '3'
services:
  openregister:
    image: openjdk:8-jre
    container_name: openregister-register
    # hack so that we wait for postgres to be available not just started
    command: bash -c '/srv/openregister-java/wait-for-it.sh postgres:5432 -- java -jar /srv/openregister-java/openregister-java.jar server /srv/openregister-java/config.yaml'
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./wait-for-it.sh:/srv/openregister-java/wait-for-it.sh:ro
      - ./config.docker.register.yaml:/srv/openregister-java/config.yaml:ro
      - ./deploy/openregister-java.jar:/srv/openregister-java/openregister-java.jar:ro
    networks:
      - openregisterjava_default

networks:
  openregisterjava_default:
    external: true
