version: '3'
services:
  openregister-java-country:
    image: openjdk:8-jre
    container_name: openregister-java-country
    # hack so that we wait for postgres to be available not just started
    command: bash -c '/srv/openregister-java/wait-for-it.sh postgres:5432 -- java -jar /srv/openregister-java/openregister-java.jar server /srv/openregister-java/config.yaml'
    ports:
      - 4011:8080
    volumes:
      - ./wait-for-it.sh:/srv/openregister-java/wait-for-it.sh:ro
      - ./config.docker.country.register.yaml:/srv/openregister-java/config.yaml:ro
      - ./deploy/openregister-java.jar:/srv/openregister-java/openregister-java.jar:ro
    networks:
      - openregister-java_default
    cap_drop:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_MODULE
          - SYS_CHROOT
          - CHOWN
          - FOWNER
          - FSETID
          - SETPCAP
          - MKNOD
          - AUDIT_WRITE
          - SETFCAP

    #healthcheck:
    #  test: ["CMD-SHELL", "curl", "-f", "http://localhost || exit 1"]
    #  interval: 1m30s
    #  timeout: 10s
    #  retries: 3
    #  start_period: 40s
        
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://openregister-java-country:8080 || exit 1"]
      interval: "1m30s"
      timeout: "10s"
      start_period: "40s"
      retries: 3

    # deploy:
    #   mode: replicated
    #   replicas: 1
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 300M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 300M

networks:
  openregister-java_default:
    external: true
