---
- hash: "c17e5f868dac5872a89707ac147a07f24f3988b7"
  entry:
    copyright: "Contains Ordnance Survey data &copy; Crown copyright & database right\
      \ 2015  \nContains National Statistics data &copy; Crown copyright & database\
      \ right 2015  \nContains Royal Mail data &copy; Royal Mail copyright & database\
      \ right 2015  \n"
    fields:
    - "address"
    - "property"
    - "street"
    - "locality"
    - "town"
    - "area"
    - "postcode"
    - "country"
    - "latitude"
    - "longitude"
    register: "address"
    registry: "ordnance-survey"
    text: "The register of places in the UK with a postal address. Some addresses\
      \ have a geographical location.\n"
  last-updated: "2015-06-02T17:42:58.755+01:00"
- hash: "b5722c61950ba170f99c5143fd1feac3bc5094dd"
  entry:
    fields:
    - "charity"
    - "name"
    - "company"
    - "start-date"
    - "end-date"
    register: "charity"
    registry: "charity-commission"
    text: "The register of UK charities.\n"
  last-updated: "2015-06-02T17:42:58.785+01:00"
- hash: "6d59f8c8603ac6410af585c3ab14c9a7ba21eeaa"
  entry:
    fields:
    - "name"
    - "company"
    - "post-town"
    - "postcode"
    - "start-date"
    - "end-date"
    register: "company"
    registry: "companies-house"
    text: "The register of UK companies.\n"
  last-updated: "2015-06-02T17:42:58.798+01:00"
- hash: "05e82a8fac07937e55571a1a8088276e2680d14e"
  entry:
    fields:
    - "country"
    - "name"
    - "official-name"
    - "citizen-names"
    - "start-date"
    - "end-date"
    - "text"
    register: "country"
    registry: "foreign-commonwealth-office"
    text: "The register of [Foreign & Commonwealth Office](https://www.gov.uk/government/organisations/foreign-commonwealth-office)\
      \ list of approved British English-language names and descriptive terms for\
      \ [countries](http://country.openregister.org) and territories of the world\
      \ and their citizens.\n"
  last-updated: "2015-06-02T17:42:58.812+01:00"
- hash: "e3185a82503621f80e8ed60891dbbcd52764cc1a"
  entry:
    fields:
    - "fields"
    - "text"
    register: "fields"
    registry: "cabinet-office"
    text: "This register of datatypes constraining a field value and idenitifying\
      \ ways in which it may be encoded a representation.\n"
  last-updated: "2015-06-02T17:42:58.826+01:00"
- hash: "e56d6a9f676ae012b64bda234757ea78bb68fd38"
  entry:
    fields:
    - "field"
    - "fields"
    - "register"
    - "cardinality"
    - "text"
    register: "field"
    registry: "cabinet-office"
    text: "The register of field names which may appear in a register.\n"
  last-updated: "2015-06-02T17:42:58.840+01:00"
- hash: "1e5b3697a1e43a13a707d76ac079b98dea05393f"
  entry:
    fields:
    - "post-town"
    - "start-date"
    - "end-date"
    - "text"
    register: "post-town"
    registry: "cabinet-office"
    text: "The register of [Post towns](http://en.wikipedia.org/wiki/Post_town) which\
      \ may appear in postal [addresses](http://address.openregister.org) in the UK.\n"
  last-updated: "2015-06-02T17:42:58.854+01:00"
- hash: "0fc4b18d1d8bae695b69bd36e1c9d6589d53247f"
  entry:
    copyright: "Contains Ordnance Survey data © Crown copyright & database right 2015\
      \  \nContains National Statistics data © Crown copyright & database right 2015\
      \  \nContains Royal Mail data © Royal Mail copyright & database right 2015 \
      \ \n"
    fields:
    - "postcode"
    - "latitude"
    - "longitude"
    register: "postcode"
    registry: "office-for-national-statistics"
    text: "The register of UK Postal codes which may appear in an [address](http://address.openregister.org).\n"
  last-updated: "2015-06-02T17:42:58.870+01:00"
- hash: "d05c06591eca2fe6a1475458017c4928bc84c765"
  entry:
    fields:
    - "public-body"
    - "name"
    - "website"
    - "public-body-type"
    - "parent-bodies"
    - "text"
    - "crest"
    register: "public-body"
    registry: "cabinet-office"
    text: "The register of UK Ministerial Departments, agencies and public bodies\
      \ sponsored by the UK government.\n"
  last-updated: "2015-06-02T17:42:58.880+01:00"
- hash: "a8311d6acc8f3d70bd43f99348ab036f1bac8e66"
  entry:
    fields:
    - "register"
    - "text"
    - "registry"
    - "copyright"
    - "fields"
    register: "register"
    registry: "cabinet-office"
    text: "The register of UK government registers.\n"
  last-updated: "2015-06-02T17:42:58.897+01:00"
- hash: "befe6cc0ea9ae3158f78e8c042f945389a59f221"
  entry:
    fields:
    - "school"
    - "name"
    - "start-date"
    - "end-date"
    - "gender"
    - "religious-character"
    - "minimum-age"
    - "maximum-age"
    - "headteacher"
    - "website"
    - "address"
    register: "school"
    registry: "department-of-education"
    text: "The register of primary, secondary and\_special needs schools in England\
      \ and Wales.\n"
  last-updated: "2015-06-02T17:42:58.910+01:00"
