mint:
  restart: always
  build: .
  expose:
    - "5672"
    - "9092"
    - "2181"
    - "2888:3888"
  links:
    - rabbitmq
    - postgres
postgres:
  restart: always
  image: postgres:latest
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: mint
    POSTGRES_PASSWORD: mint

rabbitmq:
  restart: always
  image: rabbitmq:3-management
  ports:
    - "8080:15672"
  environment:
    RABBITMQ_NODENAME: localhost
    HOSTNAME: localhost

zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181"

kafka:
  restart: always
  image: wurstmeister/kafka
  ports:
    - "9092"
  links:
    - zookeeper
  environment:
    KAFKA_ZOOKEEPER_CONNECT: zookeeper
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock