version: 0.0
os: linux
files:
  - source: /
    destination: /srv/openregister-java
hooks:
  ApplicationStop:
    - location: scripts/aws/deregister_from_elb.sh
    - location: scripts/stop-service.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/start-service.sh
    - location: scripts/aws/register_with_elb.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
      runas: root
