---
applications:
- name: discovery-multi
  memory: 1024M
  instances: 2
  buildpack: java_buildpack
  health-check-type: http
  health-check-http-endpoint: /records
  path: ../../openregister-java.jar
  routes:
    - route: address.discovery.openregister.org
    - route: clinical-commissioning-group.discovery.openregister.org
    - route: government-domain.discovery.openregister.org
    - route: green-deal-certification-body.discovery.openregister.org
    - route: jobcentre.discovery.openregister.org
    - route: local-authority-nir.discovery.openregister.org
    - route: local-authority-type.discovery.openregister.org
    - route: place.discovery.openregister.org
    - route: prison.discovery.openregister.org
    - route: statistical-geography-unitary-authority-wls.discovery.openregister.org
    - route: statistical-geography.discovery.openregister.org
    - route: street-custodian.discovery.openregister.org
    - route: street.discovery.openregister.org
    - route: uk.discovery.openregister.org
    - route: vehicle-colour.discovery.openregister.org
  services:
    - discovery-db
    - logit-ssl-drain
  env:
    JBP_CONFIG_JAVA_MAIN: '{ arguments: "server s3://openregister.discovery.config/multi/openregister/paas-config.yaml" }'
    AWS_ACCESS_KEY_ID: change-me
    AWS_SECRET_ACCESS_KEY: change-me
    AWS_REGION: eu-west-1
