---
applications:
- name: discovery-multi
  memory: 1024M
  instances: 2
  buildpack: java_buildpack
  health-check-type: http
  health-check-http-endpoint: /records
  path: ../../openregister-java.jar
  domains:
    - discovery.openregister.org
  hosts:
    - address
    - clinical-commissioning-group
    - government-domain
    - green-deal-certification-body
    - jobcentre
    - local-authority-nir
    - local-authority-type
    - place
    - prison
    - public-body
    - public-body-classification
    - statistical-geography-unitary-authority-wls
    - statistical-geography
    - street-custodian
    - street
    - uk
    - vehicle-colour
  services:
    - discovery-db
    - logit-ssl-drain
  env:
    JBP_CONFIG_JAVA_MAIN: '{ arguments: "server s3://openregister.discovery.config/multi/openregister/paas-config.yaml" }'
    AWS_ACCESS_KEY_ID: change-me
    AWS_SECRET_ACCESS_KEY: change-me
    AWS_REGION: eu-west-1
