---
applications:
- name: discovery-multi
  memory: 4GB
  instances: 2
  buildpack: java_buildpack
  health-check-type: http
  health-check-http-endpoint: /records
  path: ../../openregister-java.jar
  domains:
    - discovery.openregister.org
  hosts:
    - address
    - allergen
    - approved-meat-establishment
    - charity
    - charity-class
    - clinical-commissioning-group
    - green-deal-certification-body
    - jobcentre
    - local-authority-nir
    - local-authority-type
    - meat-establishment-operation
    - meat-establishment-outcome
    - meat-establishment-type
    - place
    - police-force
    - police-neighbourhood
    - prison
    - qualification-assessment-method
    - qualification-level
    - qualification-subject
    - qualification-type
    - street-custodian
    - street
    - uk
    - vehicle-colour
    - westminster-parliamentary-constituency
  services:
    - discovery-db
    - logit-ssl-drain
  env:
    JBP_CONFIG_JAVA_MAIN: '{ arguments: "server s3://openregister.discovery.config/multi/openregister/paas-config.yaml" }'
    AWS_ACCESS_KEY_ID: change-me
    AWS_SECRET_ACCESS_KEY: change-me
    AWS_REGION: eu-west-1
