---
applications:
- name: beta-multi
  memory: 4GB
  instances: 2
  buildpack: java_buildpack
  health-check-type: http
  health-check-http-endpoint: /records
  path: ../../openregister-java.jar
  domains:
    - beta.openregister.org
    - register.gov.uk
  hosts:
    - country
    - government-domain
    - government-organisation
    - government-service
    - internal-drainage-board
    - local-authority-eng
    - local-authority-sct
    - local-authority-type
    - principal-local-authority
    - prison-estate
    - registration-district
    - statistical-geography
    - statistical-geography-unitary-authority-wls
    - territory
  services:
    - beta-db
    - logit-ssl-drain
  env:
    JBP_CONFIG_JAVA_MAIN: '{ arguments: "server s3://openregister.beta.config/multi/openregister/paas-config.yaml" }'
    AWS_ACCESS_KEY_ID: change-me
    AWS_SECRET_ACCESS_KEY: change-me
    AWS_REGION: eu-west-1
