---
applications:
- name: alpha-multi
  memory: 4GB
  instances: 2
  buildpack: java_buildpack
  health-check-type: http
  health-check-http-endpoint: /records
  path: ../../openregister-java.jar
  domains:
    - alpha.openregister.org
  hosts:
    - industrial-classification
    - internal-drainage-board
    - occupation
    - principal-local-authority
    - public-body
    - public-body-classification
    - school-eng
    - school-type-eng
    - social-housing-provider-designation
    - social-housing-provider-legal-entity
    - social-housing-provider
  services:
    - alpha-db
    - logit-ssl-drain
  env:
    JBP_CONFIG_JAVA_MAIN: '{ arguments: "server s3://openregister.alpha.config/multi/openregister/paas-config.yaml" }'
    AWS_ACCESS_KEY_ID: change-me
    AWS_SECRET_ACCESS_KEY: change-me
    AWS_REGION: eu-west-1
