---
applications:
- name: alpha-multi
  memory: 4GB
  instances: 2
  buildpack: java_buildpack
  health-check-type: http
  health-check-http-endpoint: /records
  path: ../../openregister-java.jar
  domains:
    - alpha.openregister.org
  hosts:
    - allergen
    - industrial-classification
    - local-authority-nir
    - occupation
    - principal-local-authority
    - public-body
    - public-body-classification
    - school-eng
    - school-type-eng
    - social-housing-provider-designation
    - social-housing-provider-designation-eng
    - social-housing-provider-legal-entity
    - social-housing-provider-legal-entity-eng
    - social-housing-provider
    - social-housing-provider-eng
    - statistical-geography-council-area-sct
    - statistical-geography-county-eng
    - statistical-geography-london-borough-eng
    - statistical-geography-metropolitan-counties-eng
    - statistical-geography-metropolitan-district-eng
    - statistical-geography-registration-district-eng
    - statistical-geography-registration-district-wls
    - statistical-geography-non-metropolitan-district-eng
    - statistical-geography-unitary-authority-eng
  services:
    - alpha-db
    - logit-ssl-drain
  env:
    JBP_CONFIG_JAVA_MAIN: '{ arguments: "server s3://openregister.alpha.config/multi/openregister/paas-config.yaml" }'
    AWS_ACCESS_KEY_ID: change-me
    AWS_SECRET_ACCESS_KEY: change-me
    AWS_REGION: eu-west-1
